[package]
name = "neovm-executor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Execution engines for NeoVM compiler artifacts"

[dependencies]
cranelift-jit = "0.131.0"
cranelift-module = "0.131.0"
lasso = "0.7.3"
rug = { version = "1", default-features = false, features = ["integer", "std"] }
gmp-mpfr-sys = { version = "1.7", default-features = false, features = ["use-system-libs"] }
regex = "1"
neovm-compiler = { path = "../neovm-compiler", version = "0.0.1" }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "jit_benchmarks"
harness = false
